[package]
name = "raytrace"
version = "0.1.0"
features = ["gfx"]
edition = "2018"
build = "build.rs"

[dependencies]
rand = "0.7.3"
gl = "0.14.0"

[dependencies.sdl2]
version = "0.34.0"
default-features = false
features = ["gfx"]

[[example]]
name = "ogl"
